global: 
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gpu_exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['mlrig:port']
        labels: 
          instance: 'mlrig'
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['server_ip:port']     
        labels: 
          instance: 'server_name'
      # - targets: ['etc etc']     
      #   labels: 
      #     instance: 'etc'
